### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array. - Spatial4n.Util.GeohashUtils.DecodeBoundary

### ISSUE THREAD

**Issue by stesee** [Spatial4n/Spatial4n#1]
Sometimes under heavy load I see this in our logs:

```
 System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Spatial4n.Util.GeohashUtils.DecodeBoundary(String geohash, SpatialContext ctx)
   at Spatial4n.Util.GeohashUtils.Decode(String geohash, SpatialContext ctx)
   at Lucene.Net.Spatial.Util.ShapeFieldCacheProvider`1.<>c_DisplayClass5_0.<GetCache>b_1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Lucene.Net.Spatial.Util.ShapeFieldCacheDistanceValueSource.CachedDistanceFunctionValue..ctor(ShapeFieldCacheDistanceValueSource outerInstance, AtomicReader reader)
   at Lucene.Net.Spatial.Util.ShapeFieldCacheDistanceValueSource.GetValues(IDictionary context, AtomicReaderContext readerContext)
   at Lucene.Net.Queries.Function.FunctionQuery.AllScorer..ctor(FunctionQuery outerInstance, AtomicReaderContext context, IBits acceptDocs, FunctionWeight w, Single qWeight)
   at Lucene.Net.Queries.Function.FunctionQuery.FunctionWeight.GetScorer(AtomicReaderContext ctx, IBits acceptDocs)
   at Lucene.Net.Queries.CustomScoreQuery.CustomWeight.GetScorer(AtomicReaderContext context, IBits acceptDocs)
   at Lucene.Net.Search.Weight.GetBulkScorer(AtomicReaderContext context, Boolean scoreDocsInOrder, IBits acceptDocs)
   at Lucene.Net.Search.IndexSearcher.Search(IList`1 leaves, Weight weight, ICollector collector)
   at Lucene.Net.Search.IndexSearcher.Search(IList`1 leaves, Weight weight, ScoreDoc after, Int32 nDocs)
   at Lucene.Net.Search.IndexSearcher.Search(Weight weight, ScoreDoc after, Int32 nDocs)
```

Looking up to GeohashUtils.cs I found a comment "//TODO check **successful?"** at https://github.com/Spatial4n/Spatial4n/blob/b5dea48324d6e6423bfc2a3e2551778a4b1bbcf7/src/Spatial4n/Util/GeohashUtils.cs#L186 

I am curious if you can elaborate on the comment. Could this be related to my issue?

**Comment by NightOwl888** [comment]
`TODO` is not owned by us, that is something that was added upstream in [spatial4j](https://github.com/locationtech/spatial4j). They may also be able to assist you with this issue.
